#!/bin/sh
mkdir -p /opt/dbspace/
sqlite3 /opt/dbspace/.syspopup.db < /opt/share/syspopup_db.sql
rm -rf /opt/share/syspopup_db.sql

if [ ${USER} = "root" ]
then
	chown root:root /usr/lib/libsyspopup.so.0.1.0
	chown root:5000 /opt/dbspace/.syspopup.db
	chown root:5000 /opt/dbspace/.syspopup.db-journal
fi

chmod 644 /usr/lib/libsyspopup.so.0.1.0
chmod 664 /opt/dbspace/.syspopup.db
chmod 664 /opt/dbspace/.syspopup.db-journal



